#logLevel = "DEBUG"
graceTimeOut = "5s"
debug = false
defaultEntryPoints = ["http", "https"]

[web]
address = ":8080"

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]
    [[entryPoints.https.tls.certificates]]
    certFile = "/etc/self.crt"
    keyFile = "/etc/self.key"
  [entryPoints.transport]
    [entryPoints.transport.respondingTimeouts]
      readTimeout = 3000
      writeTimeout = 3000
      idleTimeout = 3000
  
[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "angaryos.mikrogovernment.com"
swarmmode = true
watch = true
exposedbydefault = false