version: '3.3'

services:
    geoserver:
        image: thinkwhere/geoserver:2.14
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "10"
        ports:
            - "8086:8080"
        deploy:
            placement:
                constraints:
                    - node.labels.geoserver == ok
            mode: replicated
            replicas: 1
        environment:
            - GEOSERVER_LOG_LOCATION=/opt/geoserver/data_dir/logs/geoserver.log
        volumes:
            - ./geoserver_data:/opt/geoserver/data_dir
            - ./tomcat_settings/setenv.sh:/usr/local/tomcat/bin/setenv.sh
            - ./tomcat_settings/logs:/usr/local/tomcat/logs
            - ./rasters:/root/Rasters